warewulf-vnfs 3.6 ->3.7

diff --git a/components/provisioning/warewulf-vnfs/SOURCES/warewulf-vnfs.wwmkchroot.patch b/components/provisioning/warewulf-vnfs/SOURCES/warewulf-vnfs.wwmkchroot.patch
--- a/components/provisioning/warewulf-vnfs/SOURCES/warewulf-vnfs.wwmkchroot.patch
+++ b/components/provisioning/warewulf-vnfs/SOURCES/warewulf-vnfs.wwmkchroot.patch
@@ -1,6 +1,6 @@
---- warewulf-vnfs-3.6/libexec/wwmkchroot/functions	2014-05-21 11:13:14.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/libexec/wwmkchroot/functions	2014-10-22 10:41:33.926759500 -0700
-@@ -91,7 +91,11 @@
+--- vnfs/libexec/wwmkchroot/functions	2015-08-26 19:58:46.000000000 -0700
++++ vnfs.patch/libexec/wwmkchroot/functions	2016-02-23 12:06:26.546334700 -0800
+@@ -117,7 +117,11 @@
  }
  
  configure_authentication() {
@@ -8,12 +8,12 @@
 +    if [ -x "/usr/sbin/chroot" ]; then
 +        /usr/sbin/chroot $CHROOTDIR /usr/sbin/pwconv
 +    elif [ -x "/usr/bin/chroot" ]; then
-+    	/usr/bin/chroot $CHROOTDIR /usr/sbin/pwconv
++       /usr/bin/chroot $CHROOTDIR /usr/sbin/pwconv
 +    fi
      return 0
  }
  
-@@ -156,7 +160,9 @@
+@@ -189,7 +193,9 @@
  }
  
  configure_network() {
@@ -24,8 +24,8 @@
          echo "NETWORKING=yes" > $CHROOTDIR/etc/sysconfig/network
      fi
      return 0
---- warewulf-vnfs-3.6/libexec/wwmkchroot/golden-system.tmpl	2014-05-21 11:13:14.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/libexec/wwmkchroot/golden-system.tmpl	2014-10-22 10:41:33.938261800 -0700
+--- vnfs/libexec/wwmkchroot/golden-system.tmpl	2013-08-07 20:29:18.000000000 -0700
++++ vnfs.patch/libexec/wwmkchroot/golden-system.tmpl	2016-02-23 12:07:08.447213200 -0800
 @@ -36,6 +36,7 @@
          --exclude=/var/tmp/* \
          --exclude=/var/log/* \
@@ -34,12 +34,10 @@
          root@$SOURCEADDR:/ .
  
      if [ $? -ne 0 ]; then
---- /dev/null	2014-10-22 10:55:20.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/libexec/wwmkchroot/opensuse-13.tmpl	2014-10-22 10:41:33.947263600 -0700
-@@ -0,0 +1,22 @@
-+#DESC: A clone of Red Hat Enterprise Linux 6
-+
-+# The general RHEL include has all of the necessary functions, but requires
+--- /dev/null	2016-03-04 09:47:19.000000000 -0800
++++ vnfs.patch/libexec/wwmkchroot/opensuse-13.tmpl	2016-02-23 13:38:58.416584700 -0800
+@@ -0,0 +1,20 @@
++# The general SUSE include has all of the necessary functions, but requires
 +# some basic variables specific to each chroot type to be defined.
 +. include-suse
 +
@@ -59,40 +57,42 @@
 +
 +
 +# vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
---- /dev/null	2014-10-22 10:56:15.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/libexec/wwmkchroot/include-suse	2014-10-22 10:41:33.956765500 -0700
-@@ -0,0 +1,116 @@
-+
-+
-+REPO_NAME="SUSE-Linux-Enterprise-Server-11-SP3"
-+ZYP_CONF="/root/zypp-ww.conf"
+--- /dev/null	2016-03-04 11:17:29.000000000 -0800
++++ vnfs.patch/libexec/wwmkchroot/include-suse	2016-03-04 11:16:19.597987500 -0800
+@@ -0,0 +1,105 @@
++REPO_NAME="SLES12-12-0-sp1"
++ZYP_CONF="/root/yum-ww.conf"
 +ZYP_CMD="zypper -c $CHROOTDIR/$ZYP_CONF --root $CHROOTDIR -n --gpg-auto-import-keys"
 +
-+sanity_check() {
-+    if [ ! -x $WAREWULF_PREFIX/bin/cluster-env ]; then
-+        echo "warewulf-cluster package is recommended on nodes you are building VNFS images on.";
-+        sleep 2;
-+    else
-+        $WAREWULF_PREFIX/bin/cluster-env;
-+    fi
-+
-+    if ! rpm -q zypper >/dev/null 2>&1; then
++distro_check() {
++    if ! rpm -q zypper >/dev/null 2>&1 ; then
 +        echo "ERROR: Could not query RPM for Zypper"
 +        return 1
 +    fi
 +    return 0
 +}
 +
-+prechroot() {
++set_overlay() {
++    if [ ! -d "$CHROOTDIR" -o ! -x "$CHROOTDIR/sbin/init" ]; then
++        echo "ERROR: This is an overlay that must work on an existing chroot!"
++        return 1
++    fi
++    if [ ! -f "$CHROOTDIR/etc/SuSE-release" ]; then
++        echo "ERROR: This must be a SuSE compatible chroot!"
++        return 1
++    fi
++    PKGR_CMD="$ZYP_CMD install $PKGLIST"
++    return 0
++}
 +
++prechroot() {
 +    if [ -n "$OS_MIRROR" ]; then
 +        ZYP_MIRROR="$OS_MIRROR"
 +    fi
-+
 +    if [[ -z "$ZYP_MIRROR" && -z "$INSTALL_ISO" ]]; then
 +        echo "ERROR: You must define the \$ZYP_MIRROR variable in the template"
 +        cleanup
-+        exit 1
++        return 1
 +    fi
 +
 +    VERSION=`rpm -qf /etc/SuSE-release  --qf '%{VERSION}\n'`
@@ -102,14 +102,13 @@
 +    mkdir -p $CHROOTDIR/etc/zypp
 +    mkdir -p $CHROOTDIR/dev
 +
-+    cp -rap /etc/zypp/zypper.conf /etc/zypp/repos.d $CHROOTDIR/etc/zypp/.
++    cp -rap /etc/zypp/zypper.conf /etc/zypp/repos.d $CHROOTDIR/etc
 +    sed -i -e "s/\$releasever/$VERSION/g" `find $CHROOTDIR/etc/zypp* -type f`
 +
 +    ZYP_CONF_DIRNAME=`dirname $ZYP_CONF`
 +    mkdir -m 0755 -p $CHROOTDIR/$ZYP_CONF_DIRNAME
 +
 +    > $CHROOTDIR/$ZYP_CONF
-+
 +    echo "[main]" >> $CHROOTDIR/$ZYP_CONF
 +    echo '#cachedir=/var/cache/yum/$basearch/$releasever' >> $CHROOTDIR/$ZYP_CONF
 +    echo "#keepcache=0" >> $CHROOTDIR/$ZYP_CONF
@@ -130,6 +129,7 @@
 +        echo "baseurl=$ZYP_MIRROR" >> $CHROOTDIR/$ZYP_CONF
 +        echo "enabled=1" >> $CHROOTDIR/$ZYP_CONF
 +        echo "type=rpm-md" >> $CHROOTDIR/$ZYP_CONF
++        echo "gpgcheck=0" >> $CHROOTDIR/$ZYP_CONF
 +    else
 +        for i in `ls -d $MEDIA_MOUNTPATH.*`; do
 +            if [ -z "$INSTALLDIRS" ]; then
@@ -149,27 +149,12 @@
 +        echo "baseurl=$INSTALLDIRS" >> $CHROOTDIR/$ZYP_CONF
 +        echo "enabled=1" >> $CHROOTDIR/$ZYP_CONF
 +        echo "type=rpm-md" >> $CHROOTDIR/$ZYP_CONF
++        echo "gpgcheck=0" >> $CHROOTDIR/$ZYP_CONF
 +
 +        ZYP_MIRROR=$INSTALLDIRS
 +    fi
 +
-+}
-+
-+buildchroot() {
-+
-+    if [ -z "$PKGLIST" ]; then
-+        echo "ERROR: You must define the \$PKGLIST variable in the template!"
-+        cleanup
-+        exit 1
-+    fi
-+
-+    $ZYP_CMD install -l -n $PKGLIST
-+
-+    if [ $? -ne 0 ]; then
-+        echo "ERROR: Failed to create chroot"
-+        return 1
-+    fi
-+
++    PKGR_CMD="$ZYP_CMD install $PKGLIST"
 +    return 0
 +}
 +
@@ -178,8 +163,10 @@
 +    return 0
 +}
 +
---- /dev/null	2014-10-22 10:57:03.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/libexec/wwmkchroot/sles-11.tmpl	2014-10-22 10:41:33.985771300 -0700
++
++# vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
+--- /dev/null	2016-03-04 11:17:53.000000000 -0800
++++ vnfs.patch/libexec/wwmkchroot/sles-11.tmpl	2016-02-23 13:35:39.753360000 -0800
 @@ -0,0 +1,22 @@
 +#DESC: SUSE Linux Enterprise 11SP3
 +
@@ -203,8 +190,8 @@
 +
 +
 +# vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
---- /dev/null	2014-10-22 10:57:27.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/libexec/wwmkchroot/sles-12.tmpl	2014-10-22 10:46:22.032869200 -0700
+--- /dev/null	2016-03-04 11:17:57.000000000 -0800
++++ vnfs.patch/libexec/wwmkchroot/sles-12.tmpl	2016-02-23 13:35:39.760361400 -0800
 @@ -0,0 +1,22 @@
 +#DESC: SUSE Linux Enterprise 12
 +
@@ -222,50 +209,29 @@
 +    filesystem findutils gawk grep iproute2 iputils mingetty net-tools \
 +    nfs-kernel-server pam rpcbind procps psmisc shadow rsync sed rsyslog tcpd \
 +    timezone util-linux words libz1 tar less gzip kmod-compat udev openssh \
-+    dhcp-client pciutils vim strace cron cpupower cpio wget zypper libstdc++6 libgcc_s1 libicu52_1"
++    dhcp-client pciutils vim strace cron cpupower cpio wget zypper libstdc++6 libgcc_s1"
 +
 +
 +
 +
 +# vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
---- warewulf-vnfs-3.6/libexec/wwmkchroot/Makefile.am	2014-05-21 11:13:14.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/libexec/wwmkchroot/Makefile.am	2014-10-22 10:46:50.526566800 -0700
-@@ -1,6 +1,6 @@
+--- vnfs/libexec/wwmkchroot/Makefile.am	2016-02-15 20:36:06.000000000 -0800
++++ vnfs.patch/libexec/wwmkchroot/Makefile.am	2016-03-04 11:20:01.473853800 -0800
+@@ -1,6 +1,7 @@
  wwmkchrootdir = $(libexecdir)/warewulf/wwmkchroot
  
--dist_wwmkchroot_SCRIPTS = centos-5.tmpl centos-6.tmpl include-rhel rhel-generic.tmpl sl-5.tmpl sl-6.tmpl functions include-deb debian.tmpl debian7-32.tmpl debian7-64.tmpl golden-system.tmpl
-+dist_wwmkchroot_SCRIPTS = centos-5.tmpl centos-6.tmpl include-rhel rhel-generic.tmpl sl-5.tmpl sl-6.tmpl functions include-deb debian.tmpl debian7-32.tmpl debian7-64.tmpl golden-system.tmpl include-suse opensuse-13.tmpl sles-11.tmpl sles-12.tmpl
+-dist_wwmkchroot_SCRIPTS = centos-5.tmpl centos-6.tmpl centos-7.tmpl include-rhel rhel-generic.tmpl sl-5.tmpl sl-6.tmpl sl-7.tmpl functions include-deb debian-8.tmpl debian7-32.tmpl debian7-64.tmpl golden-system.tmpl
++dist_wwmkchroot_SCRIPTS = centos-5.tmpl centos-6.tmpl centos-7.tmpl include-rhel rhel-generic.tmpl sl-5.tmpl sl-6.tmpl sl-7.tmpl functions include-deb debian-8.tmpl debian7-32.tmpl debian7-64.tmpl golden-system.tmpl include-suse opensuse-13.tmpl sles-11.tmpl sles-12.tmpl
++ 
  
  MAINTAINERCLEANFILES = Makefile.in
  
---- warewulf-vnfs-3.6/libexec/wwmkchroot/Makefile.in	2014-05-28 11:05:16.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/libexec/wwmkchroot/Makefile.in	2014-10-22 10:47:13.334127400 -0700
-@@ -143,7 +143,7 @@
- top_builddir = @top_builddir@
- top_srcdir = @top_srcdir@
- wwmkchrootdir = $(libexecdir)/warewulf/wwmkchroot
--dist_wwmkchroot_SCRIPTS = centos-5.tmpl centos-6.tmpl include-rhel rhel-generic.tmpl sl-5.tmpl sl-6.tmpl functions include-deb debian.tmpl debian7-32.tmpl debian7-64.tmpl golden-system.tmpl
-+dist_wwmkchroot_SCRIPTS = centos-5.tmpl centos-6.tmpl include-rhel rhel-generic.tmpl sl-5.tmpl sl-6.tmpl functions include-deb debian.tmpl debian7-32.tmpl debian7-64.tmpl golden-system.tmpl include-suse opensuse-13.tmpl sles-11.tmpl sles-12.tmpl
- MAINTAINERCLEANFILES = Makefile.in
- all: all-am
+--- vnfs/bin/wwbootstrap	2015-08-06 15:24:06.000000000 -0700
++++ vnfs.patch/bin/wwbootstrap	2016-03-04 11:23:42.121974600 -0800
+@@ -239,6 +239,11 @@
  
---- warewulf-vnfs-3.6/bin/wwbootstrap	2014-05-21 11:13:14.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/bin/wwbootstrap	2014-10-22 10:41:34.007775700 -0700
-@@ -20,6 +20,8 @@
- &set_log_level("NOTICE");
- 
- $ENV{"PATH"} = "/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin";
-+delete $ENV{"BASH_ENV"};
-+delete $ENV{"ENV"};
- 
- my $randstring = &rand_string("12");
- my $tmpdir = "/var/tmp/wwinitrd.$randstring";
---- warewulf-vnfs-3.6/bin/wwbootstrap     2015-11-02 13:53:51.337557568 -0800
-+++ warewulf-vnfs-3.6.patch/bin/wwbootstrap 2015-11-02 13:54:51.684878692 -0800
-@@ -232,6 +232,11 @@
-
      }
-
+ 
 +    # manually copy modules.order and modules.builtin from chroot to
 +    # suppress warning from depmod
 +    copy("$opt_chroot/lib/modules/$opt_kversion/modules.order", "$tmpdir/initramfs/lib/modules/$opt_kversion/modules.order");
@@ -274,41 +240,3 @@
      if ($module_count > 0) {
          &nprint("Number of drivers included in bootstrap: $module_count\n");
          &dprint("Running depmod\n");
---- warewulf-vnfs-3.6/bin/wwvnfs	2014-05-21 11:13:14.000000000 -0700
-+++ warewulf-vnfs-3.6.patch/bin/wwvnfs	2014-10-22 10:41:33.994773100 -0700
-@@ -265,6 +265,8 @@
- 
- &dprint("Sanitizing the PATH environment variable\n");
- $ENV{"PATH"} = "/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin";
-+delete $ENV{"BASH_ENV"};
-+delete $ENV{"ENV"};
- 
- 
- # Checking gzip command
---- /dev/null	2014-11-04 13:58:13.352043839 -0500
-+++ warewulf-vnfs-3.6.patch/libexec/wwmkchroot/centos-7.tmpl	2014-11-04 17:56:31.879873659 -0500
-@@ -0,0 +1,24 @@
-+#DESC: A clone of Red Hat Enterprise Linux 7
-+
-+# The general RHEL include has all of the necessary functions, but requires
-+# some basic variables specific to each chroot type to be defined.
-+. include-rhel
-+
-+
-+
-+# Define the location of the YUM repository
-+YUM_MIRROR="http://mirror.centos.org/centos-7/7/os/\$basearch/"
-+
-+# Install only what is necessary/specific for this distribution
-+PKGLIST="SysVinit basesystem bash redhat-release chkconfig coreutils e2fsprogs \
-+    ethtool filesystem findutils gawk grep initscripts iproute iputils \
-+    mingetty mktemp net-tools nfs-utils pam portmap procps psmisc rdate rsync \
-+    sed setup shadow-utils rsyslog tcp_wrappers tzdata util-linux words zlib \
-+    tar less gzip which util-linux module-init-tools udev openssh-clients \
-+    openssh-server dhclient pciutils vim-minimal shadow-utils strace cronie \
-+    crontabs cpuspeed cpufrequtils cpio wget yum numactl"
-+
-+
-+
-+
-+# vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
